## 2.3 Ein- und Ausgabe

In [49]:
import pandas as pd
import json
import xlsxwriter
df = pd.read_csv("../data/Library_Usage_Small.csv")

In [50]:
df.to_json("../data/Library_Usage_Small.json")

In [51]:
df2 = pd.read_json("../data/Library_Usage_Small.json")

In [52]:
df2.to_html("../data/Library_Usage_Small.html")

In [53]:
df2 = pd.read_html("../data/Library_Usage_Small.html")[0]

In [54]:
df2.to_excel(r'../data/Library_Usage_Small.xlsx')

In [56]:
df2 = pd.read_excel("../data/Library_Usage_Small.xlsx")

In [57]:
df2.to_csv("../data/Library_Usage_Small_neu.csv")

In [58]:
df2 = pd.read_csv("../data/Library_Usage_Small_neu.csv")

In [59]:
df

,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
0,1,JUVENILE,518,8,10 to 19 years,V3,Visitacion Valley,July,2016,p,phone,False,2010,False,10.0
1,1,JUVENILE,38,0,0 to 9 years,P1,Park,June,2016,z,email,True,2015,False,4.0
2,0,ADULT,38,4,10 to 19 years,N4,Noe Valley/Sally Brunn,November,2008,z,email,True,2003,False,8.0
3,0,ADULT,48,48,20 to 24 years,O7,Ortega,February,2013,p,phone,False,2004,False,10.0
4,1,JUVENILE,28,13,0 to 9 years,E9,Excelsior,June,2016,z,email,True,2014,False,11.0
5,1,JUVENILE,1,0,10 to 19 years,M4,Merced,May,2016,z,email,True,2016,False,11.0
6,1,JUVENILE,293,11,0 to 9 years,M6,Mission,June,2016,z,email,True,2014,False,8.0
7,1,JUVENILE,900,6,0 to 9 years,V3,Visitacion Valley,June,2016,a,print,False,2011,False,10.0
8,1,JUVENILE,1569,801,10 to 19 years,W4,Western Addition,July,2016,z,email,True,2009,False,8.0
9,1,JUVENILE,45,0,0 to 9 years,A5,Anza,June,2016,z,email,True,2015,False,1.0
10,1,JUVENILE,0,0,0 to 9 years,S7,Sunset,None,None,p,phone,False,2015,False,7.0
11,1,JUVENILE,73,8,0 to 9 years,P3,Parkside,July,2016,z,email,True,2015,False,4.0
12,1,JUVENILE,12,0,0 to 9 years,X,Main Library,October,2015,z,email,True,2015,False,6.0
13,2,YOUNG ADULT,26,3,10 to 19 years,M4,Merced,November,2015,z,email,True,2009,False,NaN
14,0,ADULT,0,0,10 to 19 years,M4,Merced,None,None,z,email,True,2015,True,NaN
15,3,SENIOR,18,6,75 years and over,W2,West Portal,June,2015,p,phone,False,2003,False,7.0
16,1,JUVENILE,603,0,0 to 9 years,X,Main Library,July,2016,a,print,False,2012,False,11.0
17,1,JUVENILE,0,0,0 to 9 years,A5,Anza,None,None,z,email,True,2015,False,1.0
18,1,JUVENILE,7,0,0 to 9 years,B2,Bayview/Linda Brooks-Burton,December,2013,p,phone,False,2013,False,10.0
19,3,SENIOR,0,0,75 years and over,S7,Sunset,None,None,z,email,True,2008,True,NaN

In [60]:
df2

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Patron Type Code,Patron Type Definition,Total Checkouts,Total Renewals,Age Range,Home Library Code,Home Library Definition,Circulation Active Month,Circulation Active Year,Notice Preference Code,Notice Preference Definition,Provided Email Address,Year Patron Registered,Outside of County,Supervisor District
0,0,0,0,1,JUVENILE,518,8,10 to 19 years,V3,Visitacion Valley,July,2016,p,phone,False,2010,False,10.0
1,1,1,1,1,JUVENILE,38,0,0 to 9 years,P1,Park,June,2016,z,email,True,2015,False,4.0
2,2,2,2,0,ADULT,38,4,10 to 19 years,N4,Noe Valley/Sally Brunn,November,2008,z,email,True,2003,False,8.0
3,3,3,3,0,ADULT,48,48,20 to 24 years,O7,Ortega,February,2013,p,phone,False,2004,False,10.0
4,4,4,4,1,JUVENILE,28,13,0 to 9 years,E9,Excelsior,June,2016,z,email,True,2014,False,11.0
5,5,5,5,1,JUVENILE,1,0,10 to 19 years,M4,Merced,May,2016,z,email,True,2016,False,11.0
6,6,6,6,1,JUVENILE,293,11,0 to 9 years,M6,Mission,June,2016,z,email,True,2014,False,8.0
7,7,7,7,1,JUVENILE,900,6,0 to 9 years,V3,Visitacion Valley,June,2016,a,print,False,2011,False,10.0
8,8,8,8,1,JUVENILE,1569,801,10 to 19 years,W4,Western Addition,July,2016,z,email,True,2009,False,8.0
9,9,9,9,1,JUVENILE,45,0,0 to 9 years,A5,Anza,June,2016,z,email,True,2015,False,1.0
10,10,10,10,1,JUVENILE,0,0,0 to 9 years,S7,Sunset,None,None,p,phone,False,2015,False,7.0
11,11,11,11,1,JUVENILE,73,8,0 to 9 years,P3,Parkside,July,2016,z,email,True,2015,False,4.0
12,12,12,12,1,JUVENILE,12,0,0 to 9 years,X,Main Library,October,2015,z,email,True,2015,False,6.0
13,13,13,13,2,YOUNG ADULT,26,3,10 to 19 years,M4,Merced,November,2015,z,email,True,2009,False,NaN
14,14,14,14,0,ADULT,0,0,10 to 19 years,M4,Merced,None,None,z,email,True,2015,True,NaN
15,15,15,15,3,SENIOR,18,6,75 years and over,W2,West Portal,June,2015,p,phone,False,2003,False,7.0
16,16,16,16,1,JUVENILE,603,0,0 to 9 years,X,Main Library,July,2016,a,print,False,2012,False,11.0
17,17,17,17,1,JUVENILE,0,0,0 to 9 years,A5,Anza,None,None,z,email,True,2015,False,1.0
18,18,18,18,1,JUVENILE,7,0,0 to 9 years,B2,Bayview/Linda Brooks-Burton,December,2013,p,phone,False,2013,False,10.0
19,19,19,19,3,SENIOR,0,0,75 years and over,S7,Sunset,None,None,z,email,True,2008,True,NaN